name: Workflow CI/CD

# Déclencheurs du workflow
on:
  push:
    branches: ["main"]
    paths-ignore:
      # Ignorer les modifications dans les répertoires spécifiques au rapport de couverture
      - "front/coverage/**"
      - "back/target/site/jacoco/**"
  pull_request:
    branches: ["main"]
    types:
      # Déclencher lorsque la PR est ouverte ou mise à jour
      - opened
      - synchronize
    paths-ignore:
      - "front/coverage/**"
      - "back/target/site/jacoco/**"

jobs:
  frontend_test:
    name: Frontend test and coverage report
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      # Étape 1 : Cloner le dépôt du frontend
      - name: Checkout front
        uses: actions/checkout@v4

      # Étape 2 : Gérer le cache des dépendances npm pour accélérer les builds
      - name: Cache front
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Étape 3 : Configurer Node.js
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      # Étape 4 : Installer les dépendances npm
      - name: Install Dependencies
        run: npm ci

      # Étape 5 : Construire le projet frontend
      - name: Run build
        run: npm run build

      # Étape 6 : Exécuter les tests unitaires avec rapport de couverture
      - name: Run tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      # Étape 7 : Téléverser le rapport de couverture en tant qu'artefact (conditionnée par `frontend_test`)
      - name: Upload coverage report
        needs: frontend_test
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: front/coverage/
          overwrite: true

      # Étape 8 : Ajouter et pousser le rapport dans le dépôt (conditionnée par `Upload coverage report`)
      - name: Commit and push frontend report
        needs: Upload coverage report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          git add -f coverage/
          git commit -m "Add frontend coverage report"
          git push origin main

      # Étape 9 : Analyse avec SonarCloud (conditionnée par `frontend_test`)
      - name: SonarCloud Scan
        needs: frontend_test
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=FRONT
            -Dsonar.organization=cedricfaraud
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 10 : Construire l'image Docker pour le frontend (conditionnée par `frontend_test`)
      - name: Build Docker image
        needs: frontend_test
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      # Étape 11 : Connexion à Docker Hub (conditionnée par `frontend_test`)
      - name: Log in to Docker Hub
        needs: frontend_test
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 12 : Pousser l'image Docker sur Docker Hub (conditionnée par `Log in to Docker Hub`)
      - name: Push Docker image
        needs: Log in to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  backend_test:
    name: Backend test and coverage report
    runs-on: ubuntu-latest
    needs: frontend_test # Dépend de la réussite du frontend
    defaults:
      run:
        working-directory: back
    steps:
      # Étape 1 : Cloner le dépôt du backend
      - name: Checkout back
        uses: actions/checkout@v4

      # Étape 2 : Configurer l'environnement Java avec JDK 17
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      # Étape 3 : Mise en cache des dépendances Maven
      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Cache Build Output
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Compile Java Code
        run: mvn -B clean verify

      # Étape 5 : Téléverser le rapport Jacoco en tant qu'artefact (conditionnée par `backend_test`)
      - name: Upload Jacoco Report
        needs: backend_test
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/
          overwrite: true

      # Étape 6 : Ajouter et pousser le rapport Jacoco dans le dépôt (conditionnée par `Upload Jacoco Report`)
      - name: Commit and push backend report
        needs: Upload Jacoco Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          git add -f target/site/jacoco/
          git commit -m "Add backend coverage report"
          git push origin main

      # Étape 7 : Analyse avec SonarCloud (conditionnée par `backend_test`)
      - name: Check sonar properties
        needs: backend_test
        run: cat sonar-project.properties
      - name: Analyse SonarCloud
        needs: backend_test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar

      # Étape 8 : Construire l'image Docker pour le backend (conditionnée par `backend_test`)
      - name: Build Docker image
        needs: backend_test
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      # Étape 9 : Connexion à Docker Hub (conditionnée par `backend_test`)
      - name: Log in to Docker Hub
        needs: backend_test
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 10 : Pousser l'image Docker sur Docker Hub (conditionnée par `Log in to Docker Hub`)
      - name: Push Docker image
        needs: backend_test
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
